First Day FDP


Sample Program Usibg NUmpy

In [ ]:
import numpy as np

In [ ]:
ZeroD = np.array(46)
print(type(ZeroD))

<class 'numpy.ndarray'>


In [ ]:
OneD = np.array([12,45,89,47,45,78,89])
OneD

array([12, 45, 89, 47, 45, 78, 89])

In [ ]:
TwoD=np.array([[12,12,25,45],[78,18,91,46],[4,8,9,4],[1,2,3,4]])
TwoD

array([[12, 12, 25, 45],
       [78, 18, 91, 46],
       [ 4,  8,  9,  4],
       [ 1,  2,  3,  4]])

In [ ]:
ThreeD = np.array([[[1,8,4,6],[2,8,9,7],[4,6,8,3]]])
ThreeD

array([[[1, 8, 4, 6],
        [2, 8, 9, 7],
        [4, 6, 8, 3]]])

In [ ]:
np.ndim(TwoD)

2

In [ ]:
np.size(TwoD)

16

In [ ]:
np.shape(TwoD)

(4, 4)

In [ ]:
print(type(ThreeD))

<class 'numpy.ndarray'>


In [ ]:
print(len(OneD))

7


In [ ]:
np.arange(10,30,8)

array([10, 18, 26])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros((4,4,))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(1,25,15)

array([ 1.        ,  2.71428571,  4.42857143,  6.14285714,  7.85714286,
        9.57142857, 11.28571429, 13.        , 14.71428571, 16.42857143,
       18.14285714, 19.85714286, 21.57142857, 23.28571429, 25.        ])

In [ ]:
np.linspace(4,50,7)

array([ 4.        , 11.66666667, 19.33333333, 27.        , 34.66666667,
       42.33333333, 50.        ])

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(4)

array([0.89519974, 0.65515551, 0.6152572 , 0.87925908])

In [ ]:
np.random.rand(4,2,5)

array([[[0.41573467, 0.35892201, 0.26033577, 0.10749789, 0.94255717],
        [0.95862374, 0.25411859, 0.46610363, 0.43064135, 0.07105526]],

       [[0.51615653, 0.42700708, 0.8180285 , 0.37863707, 0.68290706],
        [0.82743043, 0.48689267, 0.188044  , 0.36527562, 0.12273621]],

       [[0.71225686, 0.72557535, 0.5211568 , 0.86602521, 0.19698477],
        [0.78967771, 0.96486788, 0.80679935, 0.05912023, 0.69004146]],

       [[0.27105094, 0.22185944, 0.00724742, 0.62947561, 0.21811222],
        [0.19535453, 0.84312397, 0.61163942, 0.55193206, 0.51796928]]])

In [ ]:
np.random.randn(2)

array([1.06474619, 1.00417739])

In [ ]:
np.random.randn(3,2)

array([[-2.02748942,  0.95088907],
       [-0.26121333, -0.86781719],
       [ 0.88653002,  0.63326919]])

In [ ]:
np.random.randint(1,6)

3

In [ ]:
np.random.randint(1,6,10)

array([1, 3, 4, 2, 3, 3, 4, 5, 4, 2])

In [ ]:
b=np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
b=np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
b.shape

(15,)

In [ ]:
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [21]:
import numpy as np
np.min(b)

np.int64(1)

If  we use next day again we have to import*** numpy and Variables***

In [7]:
import numpy as np

In [20]:
b=np.arange(1,30,2)
np.min(b)

np.int64(1)

In [15]:
b=np.arange(1,30,2)
b


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [10]:
np.min(b)


np.int64(1)

In [11]:
print(np.min(b))

1


In [12]:
np.max(b)

np.int64(29)

In [13]:
b.min()

np.int64(1)

In [16]:
b.argmax()

np.int64(14)

In [17]:
b[1:4]

array([3, 5, 7])

In [18]:
b[:5]

array([1, 3, 5, 7, 9])

In [19]:
b[3:]

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])